# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(758, 472)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.plotView = QtWidgets.QGraphicsView(Form)
        self.plotView.setObjectName("plotView")
        self.horizontalLayout.addWidget(self.plotView)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.CWT = QtWidgets.QPushButton(Form)
        self.CWT.setObjectName("CWT")
        self.gridLayout.addWidget(self.CWT, 0, 0, 1, 1)
        self.HHT = QtWidgets.QPushButton(Form)
        self.HHT.setObjectName("HHT")
        self.gridLayout.addWidget(self.HHT, 0, 1, 1, 1)
        self.STFT = QtWidgets.QPushButton(Form)
        self.STFT.setObjectName("STFT")
        self.gridLayout.addWidget(self.STFT, 1, 0, 1, 1)
        self.WVD = QtWidgets.QPushButton(Form)
        self.WVD.setObjectName("WVD")
        self.gridLayout.addWidget(self.WVD, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CWT.setText(_translate("Form", "CWT"))
        self.HHT.setText(_translate("Form", "HHT"))
        self.STFT.setText(_translate("Form", "STFT"))
        self.WVD.setText(_translate("Form", "WVD"))
        self.lineEdit.setPlaceholderText(_translate("main", "请选择格式为.json的输入文件："))
        self.lineEdit_2.setPlaceholderText(_translate("main", "请选择保存文件的输出目录："))
